#!/bin/bash

if [ -f /etc/redhat-release ]; then
    INSTALL_PKG="yum install -y"
elif [ -f /etc/debian_version ]; then
    INSTALL_PKG="apt-get install"
else
    echo "I don't know what distro I'm on"
    exit 1
fi

# This is annoying; Travis-CI uses ubuntu 12.04 for its build agents
# and 12.04 doesn't have mock. 10.04 did, and 14.04 does, but not
# anything in between. So we have to just trust that libpthreads and
# libc versions are "good enough" on ubuntu to be able to run on
# Fedora, CentOS, etc.
make rpmbuild
