#!/bin/bash

set -ex

if [ -f /etc/redhat-release ]; then
    sudo yum install -y mock python-pip
    sudo pip-python install --upgrade awscli
elif [ -f /etc/debian_version ]; then
    # Ooh, this is nasty
    # Manually pre-install dependencies
    sudo apt-get install adduser python python-decoratortools rpm usermode python-iniparse \
        python-libxml2 python-rpm python-sqlite python-sqlitecachec python-urlgrabber \
        pandoc python-pip
    # ... and now install mock from lucid (winces)
    wget http://mirrors.kernel.org/ubuntu/pool/universe/y/yum-utils/yum-utils_1.1.31-2_all.deb
    wget http://mirrors.kernel.org/ubuntu/pool/universe/m/mock/mock_1.1.33-1_all.deb
    wget http://mirrors.kernel.org/ubuntu/pool/universe/y/yum/yum_3.4.3-2ubuntu1_all.deb
    # (sorry)
    sudo dpkg -i yum_3.4.3-2ubuntu1_all.deb
    sudo dpkg -i yum-utils_1.1.31-2_all.deb
    sudo dpkg -i mock_1.1.33-1_all.deb
    # oh, the horror
    sudo groupadd mock
    sudo mkdir /var/lib/mock
    sudo chgrp -R mock /var/lib/mock
    sudo chmod 2755 /var/lib/mock
    # clean up so we don't release these .debs as well
    sudo pip install --upgrade awscli
    rm *.deb
else
    echo "I don't know what distro I'm on"
    exit 1
fi

# This is annoying; Travis-CI uses ubuntu 12.04 for its build agents
# and 12.04 doesn't have mock. 10.04 did, and 14.04 does, but not
# anything in between. So the nastiness above ...
echo $TRAVIS_BUILD_NUMBER > travis_build_number
sudo make mock

if [ $? -ne 0 ]; then
    cat /var/lib/mock/epel-6-x86_64/result/*.log
    exit 1
fi

# This should go fairly smoothly, give we're building a debian pkg on a debian box
sudo make debianpkg

if [ -z "$AWS_ACCESS_KEY_ID" ]; then
    echo "NO AWS CREDENTIALS -- NOT UPLOADING TO S3"
    exit 0
fi

for pkg in *.rpm *.deb; do
    aws s3 cp $pkg s3://credulous
done
